// Code generated by stringer. DO NOT EDIT.

package xobis

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MediumAbstract-0]
	_ = x[MediumElectricity-1]
	_ = x[MediumHeatCostAllocator-4]
	_ = x[MediumCooling-5]
	_ = x[MediumHeat-6]
	_ = x[MediumGas-7]
	_ = x[MediumColdWater-8]
	_ = x[MediumHotWater-9]
	_ = x[MediumOther-15]
}

const (
	_Medium_name_0 = "MediumAbstractMediumElectricity"
	_Medium_name_1 = "MediumHeatCostAllocatorMediumCoolingMediumHeatMediumGasMediumColdWaterMediumHotWater"
	_Medium_name_2 = "MediumOther"
)

var (
	_Medium_index_0 = [...]uint8{0, 14, 31}
	_Medium_index_1 = [...]uint8{0, 23, 36, 46, 55, 70, 84}
)

func (i Medium) String() string {
	switch {
	case i <= 1:
		return _Medium_name_0[_Medium_index_0[i]:_Medium_index_0[i+1]]
	case 4 <= i && i <= 9:
		i -= 4
		return _Medium_name_1[_Medium_index_1[i]:_Medium_index_1[i+1]]
	case i == 15:
		return _Medium_name_2
	default:
		return "Medium(" + strconv.FormatUint(uint64(i), 10) + ")"
	}
}
