// Code generated by stringer. DO NOT EDIT.

package xobis

import (
	"math/bits"
	"strconv"
	"strings"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PresentA-1]
	_ = x[PresentB-2]
	_ = x[PresentC-4]
	_ = x[PresentD-8]
	_ = x[PresentE-16]
	_ = x[PresentF-32]
}

const (
	_Presence_name_0 = "PresentAPresentBPresentCPresentDPresentEPresentF"
)

var (
	_Presence_index_0 = [...]uint8{0, 8, 16, 24, 32, 40, 48}
)

func (i Presence) ActiveFlags() []string {
	s := make([]string, 0, bits.OnesCount64(uint64(i)))
	if i&1 != 0 {
		i, s = i&^1, append(s, _Presence_name_0[_Presence_index_0[0]:_Presence_index_0[1]])
	}
	if i&2 != 0 {
		i, s = i&^2, append(s, _Presence_name_0[_Presence_index_0[1]:_Presence_index_0[2]])
	}
	if i&4 != 0 {
		i, s = i&^4, append(s, _Presence_name_0[_Presence_index_0[2]:_Presence_index_0[3]])
	}
	if i&8 != 0 {
		i, s = i&^8, append(s, _Presence_name_0[_Presence_index_0[3]:_Presence_index_0[4]])
	}
	if i&16 != 0 {
		i, s = i&^16, append(s, _Presence_name_0[_Presence_index_0[4]:_Presence_index_0[5]])
	}
	if i&32 != 0 {
		i, s = i&^32, append(s, _Presence_name_0[_Presence_index_0[5]:_Presence_index_0[6]])
	}
	if i != 0 {
		s = append(s, "Presence("+strconv.FormatUint(uint64(i), 10)+")")
	}
	return s
}

func (i Presence) String() string {
	return strings.Join(i.ActiveFlags(), "+")
}

func (i Presence) PresentA() bool {
	return i&PresentA == PresentA
}

func (i Presence) SetPresentA() Presence {
	return i | PresentA
}

func (i Presence) ClearPresentA() Presence {
	return i & ^PresentA
}

func (i Presence) PresentB() bool {
	return i&PresentB == PresentB
}

func (i Presence) SetPresentB() Presence {
	return i | PresentB
}

func (i Presence) ClearPresentB() Presence {
	return i & ^PresentB
}

func (i Presence) PresentC() bool {
	return i&PresentC == PresentC
}

func (i Presence) SetPresentC() Presence {
	return i | PresentC
}

func (i Presence) ClearPresentC() Presence {
	return i & ^PresentC
}

func (i Presence) PresentD() bool {
	return i&PresentD == PresentD
}

func (i Presence) SetPresentD() Presence {
	return i | PresentD
}

func (i Presence) ClearPresentD() Presence {
	return i & ^PresentD
}

func (i Presence) PresentE() bool {
	return i&PresentE == PresentE
}

func (i Presence) SetPresentE() Presence {
	return i | PresentE
}

func (i Presence) ClearPresentE() Presence {
	return i & ^PresentE
}

func (i Presence) PresentF() bool {
	return i&PresentF == PresentF
}

func (i Presence) SetPresentF() Presence {
	return i | PresentF
}

func (i Presence) ClearPresentF() Presence {
	return i & ^PresentF
}
